"""init

Revision ID: 1642933475f
Revises: None
Create Date: 2015-12-26 00:42:42.866511

"""

# revision identifiers, used by Alembic.
revision = '1642933475f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=True),
    sa.Column('humanized', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('nickname', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.String(length=16), nullable=True),
    sa.Column('auth_code', sa.String(length=16), nullable=True),
    sa.Column('github_id', sa.String(length=32), nullable=True),
    sa.Column('github_login', sa.String(length=64), nullable=True),
    sa.Column('github_name', sa.String(length=32), nullable=True),
    sa.Column('github_email', sa.String(length=64), nullable=True),
    sa.Column('qiniu_id', sa.String(length=32), nullable=True),
    sa.Column('qiniu_name', sa.String(length=16), nullable=True),
    sa.Column('qiniu_email', sa.String(length=32), nullable=True),
    sa.Column('api_key', sa.String(length=128), nullable=True),
    sa.Column('stream_id', sa.String(length=64), nullable=True),
    sa.Column('stream_status', sa.Integer(), nullable=True),
    sa.Column('get_auth_code_count', sa.Integer(), nullable=True),
    sa.Column('last_get_auth_code_at', sa.DateTime(), nullable=True),
    sa.Column('sign_in_count', sa.Integer(), nullable=True),
    sa.Column('current_sign_in_at', sa.DateTime(), nullable=True),
    sa.Column('last_sign_in_at', sa.DateTime(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('qiniu_id')
    )
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('thumbnail', sa.String(length=128), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('stream_id', sa.String(length=64), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('orientation', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(length=16), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel')
    op.drop_table('user')
    op.drop_table('setting')
    ### end Alembic commands ###
