"""add complaint handler

Revision ID: 19a2c55adb6c
Revises: 4979430b7dbf
Create Date: 2016-01-15 14:46:05.555079

"""

# revision identifiers, used by Alembic.
revision = '19a2c55adb6c'
down_revision = '4979430b7dbf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint', sa.Column('handler_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'complaint', 'user', ['handler_id'], ['id'])
    op.drop_column('complaint', 'is_read')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint', sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'complaint', type_='foreignkey')
    op.drop_column('complaint', 'handler_id')
    ### end Alembic commands ###
