"""channel add like

Revision ID: 1fa2a3b23f94
Revises: 2d5679b9aef6
Create Date: 2016-01-04 13:28:54.727709

"""

# revision identifiers, used by Alembic.
revision = '1fa2a3b23f94'
down_revision = '2d5679b9aef6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_user_like',
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_user_like')
    ### end Alembic commands ###
