"""update users add oauth_code

Revision ID: 2d5679b9aef6
Revises: 1642933475f
Create Date: 2016-01-01 09:54:26.990086

"""

# revision identifiers, used by Alembic.
revision = '2d5679b9aef6'
down_revision = '1642933475f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=128), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('relative_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'user', sa.Column('api_token', sa.String(length=128), nullable=True))
    op.add_column(u'user', sa.Column('last_send_message_at', sa.DateTime(), nullable=True))
    op.add_column(u'user', sa.Column('oauth_code', sa.String(length=32), nullable=True))
    op.add_column(u'user', sa.Column('rong_cloud_token', sa.String(length=128), nullable=True))
    op.drop_column(u'user', 'api_key')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('api_key', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column(u'user', 'rong_cloud_token')
    op.drop_column(u'user', 'oauth_code')
    op.drop_column(u'user', 'last_send_message_at')
    op.drop_column(u'user', 'api_token')
    op.drop_table('message')
    ### end Alembic commands ###
