"""init

Revision ID: 48addea83a97
Revises: None
Create Date: 2016-01-05 23:04:06.441677

"""

# revision identifiers, used by Alembic.
revision = '48addea83a97'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=True),
    sa.Column('humanized', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('nickname', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.String(length=16), nullable=True),
    sa.Column('auth_code', sa.String(length=16), nullable=True),
    sa.Column('github_id', sa.String(length=32), nullable=True),
    sa.Column('github_login', sa.String(length=64), nullable=True),
    sa.Column('github_name', sa.String(length=32), nullable=True),
    sa.Column('github_email', sa.String(length=64), nullable=True),
    sa.Column('qiniu_id', sa.String(length=32), nullable=True),
    sa.Column('qiniu_name', sa.String(length=16), nullable=True),
    sa.Column('qiniu_email', sa.String(length=32), nullable=True),
    sa.Column('oauth_code', sa.String(length=128), nullable=True),
    sa.Column('api_token', sa.String(length=128), nullable=True),
    sa.Column('rong_cloud_token', sa.String(length=128), nullable=True),
    sa.Column('stream_id', sa.String(length=64), nullable=True),
    sa.Column('stream_status', sa.Integer(), nullable=True),
    sa.Column('get_auth_code_count', sa.Integer(), nullable=True),
    sa.Column('last_get_auth_code_at', sa.DateTime(), nullable=True),
    sa.Column('sign_in_count', sa.Integer(), nullable=True),
    sa.Column('current_sign_in_at', sa.DateTime(), nullable=True),
    sa.Column('last_sign_in_at', sa.DateTime(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('last_send_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('qiniu_id')
    )
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('thumbnail', sa.String(length=128), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('stream_id', sa.String(length=64), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('orientation', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(length=16), nullable=True),
    sa.Column('visit_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_user_like',
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('reason_type', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=128), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('offset', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('complaint')
    op.drop_table('channel_user_like')
    op.drop_table('channel')
    op.drop_table('user')
    op.drop_table('setting')
    ### end Alembic commands ###
