"""add user column is_stream_enabled

Revision ID: 4979430b7dbf
Revises: 319c576b301f
Create Date: 2016-01-14 14:39:33.752560

"""

# revision identifiers, used by Alembic.
revision = '4979430b7dbf'
down_revision = '319c576b301f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_stream_enabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_stream_enabled')
    ### end Alembic commands ###
